/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PersonalizedRouteImport } from './routes/personalized'
import { Route as LunaRouteImport } from './routes/luna'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CertifiedRouteImport } from './routes/certified'
import { Route as BuildCourseRouteImport } from './routes/build-course'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as AdaptiveTestsRouteImport } from './routes/adaptive-tests'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizedRoute = PersonalizedRouteImport.update({
  id: '/personalized',
  path: '/personalized',
  getParentRoute: () => rootRouteImport,
} as any)
const LunaRoute = LunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CertifiedRoute = CertifiedRouteImport.update({
  id: '/certified',
  path: '/certified',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildCourseRoute = BuildCourseRouteImport.update({
  id: '/build-course',
  path: '/build-course',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptiveTestsRoute = AdaptiveTestsRouteImport.update({
  id: '/adaptive-tests',
  path: '/adaptive-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adaptive-tests': typeof AdaptiveTestsRoute
  '/battles': typeof BattlesRoute
  '/build-course': typeof BuildCourseRoute
  '/certified': typeof CertifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/luna': typeof LunaRoute
  '/personalized': typeof PersonalizedRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adaptive-tests': typeof AdaptiveTestsRoute
  '/battles': typeof BattlesRoute
  '/build-course': typeof BuildCourseRoute
  '/certified': typeof CertifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/luna': typeof LunaRoute
  '/personalized': typeof PersonalizedRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adaptive-tests': typeof AdaptiveTestsRoute
  '/battles': typeof BattlesRoute
  '/build-course': typeof BuildCourseRoute
  '/certified': typeof CertifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/luna': typeof LunaRoute
  '/personalized': typeof PersonalizedRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adaptive-tests'
    | '/battles'
    | '/build-course'
    | '/certified'
    | '/forgot-password'
    | '/forum'
    | '/login'
    | '/luna'
    | '/personalized'
    | '/progress'
    | '/reset-password'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adaptive-tests'
    | '/battles'
    | '/build-course'
    | '/certified'
    | '/forgot-password'
    | '/forum'
    | '/login'
    | '/luna'
    | '/personalized'
    | '/progress'
    | '/reset-password'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/adaptive-tests'
    | '/battles'
    | '/build-course'
    | '/certified'
    | '/forgot-password'
    | '/forum'
    | '/login'
    | '/luna'
    | '/personalized'
    | '/progress'
    | '/reset-password'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptiveTestsRoute: typeof AdaptiveTestsRoute
  BattlesRoute: typeof BattlesRoute
  BuildCourseRoute: typeof BuildCourseRoute
  CertifiedRoute: typeof CertifiedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ForumRoute: typeof ForumRoute
  LoginRoute: typeof LoginRoute
  LunaRoute: typeof LunaRoute
  PersonalizedRoute: typeof PersonalizedRoute
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalized': {
      id: '/personalized'
      path: '/personalized'
      fullPath: '/personalized'
      preLoaderRoute: typeof PersonalizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna': {
      id: '/luna'
      path: '/luna'
      fullPath: '/luna'
      preLoaderRoute: typeof LunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certified': {
      id: '/certified'
      path: '/certified'
      fullPath: '/certified'
      preLoaderRoute: typeof CertifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-course': {
      id: '/build-course'
      path: '/build-course'
      fullPath: '/build-course'
      preLoaderRoute: typeof BuildCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adaptive-tests': {
      id: '/adaptive-tests'
      path: '/adaptive-tests'
      fullPath: '/adaptive-tests'
      preLoaderRoute: typeof AdaptiveTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptiveTestsRoute: AdaptiveTestsRoute,
  BattlesRoute: BattlesRoute,
  BuildCourseRoute: BuildCourseRoute,
  CertifiedRoute: CertifiedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ForumRoute: ForumRoute,
  LoginRoute: LoginRoute,
  LunaRoute: LunaRoute,
  PersonalizedRoute: PersonalizedRoute,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
